apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: citus-worker
  template:
    metadata:
      labels:
        app: citus-worker
    spec:
      containers:
      - name: citus-worker
        image: citusdata/citus:12.1.0-alpine
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: citus-secrets
              key: postgres-password
        - name: CITUS_WORKER_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 5432
