# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2
    # vb.gui = true
  end

  (1..3).each do |i|
    config.vm.define "etcd-0#{i}" do |node|
      node.vm.hostname = "etcd-0#{i}"
      node.vm.network "private_network", ip: "192.168.0.1#{i}", virtualbox__intnet: "net-1"
      node.vm.provision "shell", path: "prov-etcd.sh"
    end
  end

  (1..3).each do |i|
    config.vm.define "pgsql-0#{i}" do |node|
      node.vm.hostname = "pgsql-0#{i}"
      node.vm.network "private_network", ip: "192.168.0.2#{i}", virtualbox__intnet: "net-1"
      node.vm.provision "shell", path: "prov-patroni.sh"
      node.vm.provision "shell", path: "prov-pgbouncer.sh"
      end
  end

  (1..1).each do |i|
    config.vm.define "haproxy-0#{i}" do |node|
      node.vm.hostname = "haproxy-0#{i}"
      node.vm.network "private_network", ip: "192.168.0.3#{i}", virtualbox__intnet: "net-1"
      node.vm.provision "shell", path: "prov-haproxy.sh"
      end
  end

  config.vm.define "client" do |node|
    node.vm.hostname = "client"
    node.vm.network "private_network", ip: "192.168.0.99", virtualbox__intnet: "net-1"
    node.vm.provision "shell", inline: "sudo apt update && sudo apt upgrade -y && sudo apt install -y postgresql-client-common && sudo apt install postgresql-client -y"
  end

  

end
